Feature/initial api
VNG-Realisatie/gemma-klantcontactcomponent pull request #1
Opened 2019-10-17 15:00 UTC by annashamray

Changes:
1. Create `Klant` resource 
1. Create `ContactMoment` resources

Issues:
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/7 (Create API)
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1308 (add `ContactMoment.kanaal` field)
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1307 (add `ContactMoment.text` field)
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1309 (add `ContactMoment.datumtijd` field)
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1317 (add `ContactMoment.initiatiefnemer` field)
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1318 (make `ContactMoment.klant` an optional field)
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1323 (add `ContactMoment.zaak` field) 
1. https://github.com/VNG-Realisatie/gemma-zaken/issues/1321 (add `Klant` attributes: `voornaam`, `achternaam`, `adres`, `telefoonnummer`, `emailadres`)

2019-10-21 10:06 UTC, joeribekker requested changes
Looking good!

2019-10-21 10:06 UTC, joeribekker commented on src/kcc/api/serializers.py
> +            "text",
Please rename to "tekst"

2019-10-21 10:06 UTC, joeribekker commented on src/kcc/api/serializers.py
> +            "klant",
Klant should have the usual help text that goes for relations:

URL-referentie naar een KLANT ...

2019-10-21 10:06 UTC, joeribekker commented on src/kcc/api/viewsets.py
>      create:
retrieve description missing

2019-10-21 10:06 UTC, joeribekker commented on src/kcc/api/viewsets.py
> +    create:
retrieve description missing.

2019-10-21 10:06 UTC, joeribekker commented on src/kcc/datamodel/models.py
> +    initiatiefnemer = models.CharField(
missing help text:

"De partij die het contact heeft geïnitieerd."

2019-10-21 10:07 UTC, joeribekker commented on src/kcc/api/serializers.py
> +            "initiatiefnemer",
This one "InitiatiefNemer" seems missing in the API spec.

2019-10-21 13:06 UTC, annashamray commented on src/kcc/api/serializers.py
> +            "text",
done

2019-10-21 13:06 UTC, annashamray commented on src/kcc/api/viewsets.py
>      create:
"retrieve" description is added

2019-10-21 13:06 UTC, annashamray commented on src/kcc/api/viewsets.py
> +    create:
"retrieve" description is added

2019-10-21 13:06 UTC, annashamray commented on src/kcc/datamodel/models.py
> +    initiatiefnemer = models.CharField(
help_text for `initiatiefnemer` is added

2019-10-21 13:06 UTC, annashamray commented on src/kcc/api/serializers.py
> +            "klant",
help_text for `klant` is added

2019-10-21 13:06 UTC, annashamray commented on src/kcc/api/serializers.py
> +            "initiatiefnemer",
API spec is regenerated, thanks for noticing

2019-10-22 10:29 UTC, joeribekker approved these changes

2019-10-22 10:29 UTC, merged