[WIP] Feature/klant betrokkene
VNG-Realisatie/gemma-klantcontactcomponent pull request #2
Opened 2019-10-18 15:50 UTC by annashamray

Depends on: https://github.com/VNG-Realisatie/gemma-klantcontactcomponent/pull/1
Schema: https://github.com/VNG-Realisatie/gemma-zaken/issues/1323#issuecomment-540012153
Issue: https://github.com/VNG-Realisatie/gemma-zaken/issues/1366

2019-10-23 11:00 UTC, joeribekker submitted a review, later dismissed
I think a rebase will remedy the issues

2019-10-23 12:11 UTC, annashamray commented
> I think a rebase will remedy the issues

the branche is rebased

2019-10-24 09:10 UTC, stevenbal requested changes

2019-10-24 09:10 UTC, stevenbal commented on src/kcc/datamodel/models.py
>      telefonnummer = models.CharField(max_length=20, blank=True)
```suggestion
    telefoonnummer = models.CharField(max_length=20, blank=True)
```

2019-10-24 09:10 UTC, stevenbal commented on src/kcc/api/tests/test_klant.py
> +        response = self.client.patch(
you could maybe add tests for `PUT` as well, just to be sure

2019-10-24 10:42 UTC, annashamray commented on src/kcc/api/tests/test_klant.py
> +        response = self.client.patch(
tests for `PUT` are added

2019-10-24 11:53 UTC, stevenbal approved these changes

2019-10-28 11:37 UTC, sergei-maertens approved these changes

2019-10-28 11:38 UTC, merged