Synchronization with ZaakContactMoment in ZRC
VNG-Realisatie/gemma-klantcontactcomponent pull request #4
Opened 2019-10-23 15:25 UTC by annashamray

Depends on: https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/126
Issue: https://github.com/VNG-Realisatie/gemma-zaken/issues/1323

2019-10-25 14:01 UTC, stevenbal requested changes

2019-10-25 14:01 UTC, stevenbal commented on src/kcc/api/tests/test_contactmoment.py
> +# from vng_api_common.models import APICredential
Since this is commented out: can this be removed or is this needed for something?

2019-10-25 14:01 UTC, stevenbal commented on src/kcc/api/tests/test_contactmoment_sync.py
> +    def test_delete_sync(self):
I would also expect a test for deleting where the sync fails

2019-10-28 11:17 UTC, sergei-maertens commented
@annashamray I just had a discussion with @joeribekker - we realized something went wrong in the communication.

We don't want to keep `zaak` information on the `ContactMoment` resource. The resources in this API are _very_ decoupled/standalone.

However, it should be possible from the Zaken API to attach zero or multiple `ContactMoment`en to a Zaak, and this relation information should be synchronised. This also means that a `ContactMoment` can be connected to multiple, different `Zaken`.

2019-10-28 11:17 UTC, closed without merging